### ISSUE TITLE
[バグ]時空間情報部で新しくjsonファイルが作られてない

### ISSUE THREAD

**Issue by kaichan1224** [kaichan1224/garimuki#9]
- Unity実行時に、FileNotFoundException: Could not find file "/Users/kosakana1224/Library/Application Support/DefaultCompany/kodo1B/2023-06-08.json"のエラーが出る
- SpaceTimeDataManagerの中の処理がうまくいってない
- そのため実行すると一時停止されてしまうが、もう一度ボタン押せばゲーム再開できます。

**Comment by pchan339** [comment]
start関数内の処理に//が入っており、処理が何もない状態だったので//を除去しました。確認お願いします。

**Comment by kaichan1224** [comment]
エラーが出る場所を探す時にコメントアウトしただけだったので気にしなくて大丈夫です。エラーは出なくなりましたか?

**Comment by kaichan1224** [comment]
- playerprefに変更(参照元のファイルがわかりにくいため)
-  class SpaceTimeData {List<SpaceTimeOneData>}をデータ化することができる?
- 自作クラスのリストを保存する方法がわからない

**Comment by kaichan1224** [comment]
リストのデータ化できてたけど、呼び出し方のミスだった
